/**
 * Procedural surface detail.
 *
 * Everything the 3D world is made of is generated at runtime. That is a
 * deliberate constraint rather than a shortcut: this repository is going to
 * be public, and every downloaded texture is a licence to check, attribute
 * and defend. Generated bytes have no such problem.
 *
 * The functions here are deterministic, so a given seed always produces the
 * same surface and screenshots stay comparable between runs.
 */

/** Cheap 2D value noise with a hashed lattice. */
function hash2(x: number, y: number, seed: number): number {
  let n = (Math.imul(x, 374761393) + Math.imul(y, 668265263) + Math.imul(seed, 1442695041)) | 0;
  n = Math.imul(n ^ (n >>> 13), 1274126177);
  return ((n ^ (n >>> 16)) >>> 0) / 4294967296;
}

function smoothstep(t: number): number {
  return t * t * (3 - 2 * t);
}

function valueNoise(x: number, y: number, seed: number): number {
  const xi = Math.floor(x);
  const yi = Math.floor(y);
  const xf = x - xi;
  const yf = y - yi;
  const u = smoothstep(xf);
  const v = smoothstep(yf);

  const a = hash2(xi, yi, seed);
  const b = hash2(xi + 1, yi, seed);
  const c = hash2(xi, yi + 1, seed);
  const d = hash2(xi + 1, yi + 1, seed);

  return (a * (1 - u) + b * u) * (1 - v) + (c * (1 - u) + d * u) * v;
}

export interface FbmOptions {
  readonly octaves?: number;
  readonly frequency?: number;
  readonly lacunarity?: number;
  readonly gain?: number;
  readonly seed?: number;
  /** Absolute-value folding, which produces creases and ridges. */
  readonly ridged?: boolean;
}

/** Fractal noise in 0..1, tiling is not guaranteed but the seam is hidden. */
export function fbm2(x: number, y: number, options: FbmOptions = {}): number {
  const {
    octaves = 5,
    frequency = 1,
    lacunarity = 2.03,
    gain = 0.5,
    seed = 1,
    ridged = false,
  } = options;

  let amplitude = 1;
  let f = frequency;
  let sum = 0;
  let norm = 0;

  for (let i = 0; i < octaves; i++) {
    const raw = valueNoise(x * f, y * f, seed + i * 131);
    const shaped = ridged ? 1 - Math.abs(raw * 2 - 1) : raw;
    sum += shaped * amplitude;
    norm += amplitude;
    amplitude *= gain;
    f *= lacunarity;
  }

  return sum / norm;
}

/**
 * A tiling height field rendered into a canvas.
 *
 * Tiling matters: the terrain uses world-space UVs, so a non-tiling detail
 * map shows a hard grid line every few metres. The four-corner blend below
 * is the standard trick and costs one extra evaluation per axis.
 */
export function heightCanvas(
  size: number,
  scale: number,
  options: FbmOptions = {},
): Float32Array {
  const out = new Float32Array(size * size);
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const u = (x / size) * scale;
      const v = (y / size) * scale;
      // Blend the field with itself shifted by one period on each axis, so
      // the left edge matches the right and the top matches the bottom.
      const fx = x / size;
      const fy = y / size;
      const a = fbm2(u, v, options);
      const b = fbm2(u - scale, v, options);
      const c = fbm2(u, v - scale, options);
      const d = fbm2(u - scale, v - scale, options);
      const top = a * (1 - fx) + b * fx;
      const bottom = c * (1 - fx) + d * fx;
      out[y * size + x] = top * (1 - fy) + bottom * fy;
    }
  }
  return out;
}

/**
 * Convert a height field into a tangent-space normal map canvas.
 *
 * `strength` is not a free dial. The encoded normal is
 * `normalize(-dx, -dy, 1)`, so as the gradient grows the Z component falls
 * towards zero, and a tangent-space normal with no Z is perpendicular to the
 * surface it is supposed to perturb. Past roughly 4 the shading normal points
 * sideways almost everywhere and the surface stops responding to light at
 * all: the result is not "very bumpy", it is unlit.
 *
 * This one cost a long detour. The terrain rendered dark and did not brighten
 * when the sun intensity was raised fivefold, which looks exactly like a
 * shadow bug. Shadows were ruled out three times before the material itself
 * was swapped for a stock one, which came out seven times brighter on the
 * same geometry under the same lights.
 *
 * `meanZ` is returned so a caller can assert the map is still dominated by
 * its own normal direction.
 */
export function normalMapCanvas(
  height: Float32Array,
  size: number,
  strength: number,
): { canvas: HTMLCanvasElement; meanZ: number } {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  const image = ctx.createImageData(size, size);
  const at = (x: number, y: number) =>
    height[((y + size) % size) * size + ((x + size) % size)]!;

  let zSum = 0;
  for (let y = 0; y < size; y++) {
    for (let x = 0; x < size; x++) {
      const dx = (at(x + 1, y) - at(x - 1, y)) * strength;
      const dy = (at(x, y + 1) - at(x, y - 1)) * strength;
      // Normalise (-dx, -dy, 1) and pack into 0..255.
      const len = Math.hypot(dx, dy, 1);
      const nz = 1 / len;
      zSum += nz;
      const i = (y * size + x) * 4;
      image.data[i] = Math.round(((-dx / len) * 0.5 + 0.5) * 255);
      image.data[i + 1] = Math.round(((-dy / len) * 0.5 + 0.5) * 255);
      image.data[i + 2] = Math.round((nz * 0.5 + 0.5) * 255);
      image.data[i + 3] = 255;
    }
  }
  ctx.putImageData(image, 0, 0);
  return { canvas, meanZ: zSum / (size * size) };
}

/** Convert a height field into a single-channel greyscale canvas. */
export function greyCanvas(
  height: Float32Array,
  size: number,
  low: number,
  high: number,
): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = size;
  canvas.height = size;
  const ctx = canvas.getContext('2d')!;
  const image = ctx.createImageData(size, size);
  for (let i = 0; i < height.length; i++) {
    const v = Math.round((low + (high - low) * height[i]!) * 255);
    image.data[i * 4] = v;
    image.data[i * 4 + 1] = v;
    image.data[i * 4 + 2] = v;
    image.data[i * 4 + 3] = 255;
  }
  ctx.putImageData(image, 0, 0);
  return canvas;
}
